// master-thesis-react/src/App.tsx
import { useState } from "react";
import "../../style.css";

interface DataElement {
  id: number;
  label: string;
}

function App() {
  let ID: number = 1;
  const data = (count: number) => {
    const data: DataElement[] = [];
    for (let i = ID - 1; i < count; ++i) {
      data.push({
        id: ID++,
        label: " I will eat " + ID + " apples",
      });
    }

    return data;
  };

  const [tableRows, setTableRows] = useState<DataElement[] | undefined>([]);
  const createTableRows = (count: number) => {
    setTableRows(data(count));
  };

  const appendTableRows = (count: number) => {
    if (tableRows === undefined) return;
    setTableRows([...tableRows, ...data(count)]);
  };

  const removeAll = () => {
    ID = 1;
    setTableRows(undefined);
    setSelectedRow(undefined);
  };

  const remove = (id: number) => {
    if (tableRows === undefined) return;
    const array = tableRows.filter(
      (dataElement: DataElement) => dataElement.id !== id
    );

    setTableRows(array);
    if (selectedRow === id) setSelectedRow(undefined);
  };

  const [selectedRow, setSelectedRow] = useState<number | undefined>(undefined);
  const select = (id: number) => {
    setSelectedRow(id);
  };

  const update5thRow = () => {
    if (tableRows === undefined) return;
    const _tableRows = [...tableRows];
    for (let i = 0; i < _tableRows.length; i += 5) {
      _tableRows[i].label = "Updated!";
    }

    setTableRows(_tableRows);
  };
  return (
    <>
      <div>
        React ts Benchmark
        <button onClick={() => createTableRows(5000)}>Create 5000 rows</button>
        <button onClick={() => appendTableRows(5000)}>Append 50000 rows</button>
        <button onClick={() => createTableRows(100000)}>Create 500000 rows</button>
        <button onClick={() => update5thRow()}>Update every 5th row</button>
        <button onClick={() => removeAll()}>Remove all rows</button>
        <button>Swap rows</button>
        {selectedRow ? <div>{"Selected: " + selectedRow}</div> : null}
      </div>
      <div>
        <table>
          <tbody>
            <div>
              <th>ID</th>
              <th>Description</th>
            </div>
            {tableRows?.map((tableRow) => (
              <>
                <tr>
                  <a>{tableRow.id}</a>
                  <a>{tableRow.label}</a>
                  <button onClick={() => select(tableRow.id)}>Select</button>
                  <button onClick={() => remove(tableRow.id)}>Remove</button>
                </tr>
              </>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}

export default App;

// master-thesis-vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'

interface DataElement {
  id: number
  label: string
}

let ID: number = 1
const data = (count: number) => {
  const data: DataElement[] = []
  for (let i = 0; i < count; ++i) {
    data.push({
      id: ID++,
      label: ' I will eat ' + ID + ' apples'
    })
  }

  return data
}

const tableRows = ref()
const createTableRows = (count: number) => {
  tableRows.value = data(count)
}

const appendTableRows = (count: number) => {
  tableRows.value.push(...data(count))
}

const removeAll = () => {
  tableRows.value.length = 0
  ID = 1
  selectedRow.value = undefined
}

const remove = (id: number) => {
  tableRows.value = tableRows.value.filter((dataElement: DataElement) => dataElement.id !== id)
  if (selectedRow.value.id === id) selectedRow.value = undefined
}

const selectedRow = ref()
const select = (id: number) => {
  selectedRow.value = id
}

const update5thRow = () => {
  const _tableRows = tableRows.value
  for (let i = 0; i < _tableRows.length; i += 5) {
    _tableRows[i].label = 'Updated!'
  }

  tableRows.value = _tableRows
}

</script>

<template>
  <div>
    Vue.js Benchmark
    <button @click="createTableRows(10000)">
      Create 50000 rows
    </button>
    <button @click="appendTableRows(10000)">
      Append 50000 rows
    </button>
    <button @click="createTableRows(100000)">
      Create 500000 rows
    </button>
    <button @click="update5thRow">
      Update every 5th row
    </button>
    <button @click="removeAll">
      Remove all rows
    </button>
    <button>
      Swap rows
    </button>
    <div v-if="selectedRow">
      {{ 'Selected: ' + selectedRow }}
    </div>
  </div>
  <div>
    <table>
      <tbody>
        <div>
          <th>ID</th>
          <th>Description</th>
        </div>
        <tr
          v-for="tableRow in tableRows"
          :key="tableRow.id"
        >
          <a>{{ tableRow.id }}</a>
          <a>{{ tableRow.label }}</a>
          <button @click="select(tableRow.id)">
            Select
          </button>
          <button @click="remove(tableRow.id)">
            Remove
          </button>
        </tr>
      </tbody>
    </table>
  </div>
</template>
